import { pathToFileURL } from 'node:url';

interface AcceptanceArticle {
  content: string;
  published_at: string;
  slug?: string;
  status: 'draft' | 'scheduled';
  summary: string;
  template: 'diary';
  theme: string;
  title: string;
}

export function buildAcceptanceFixtures(now: Date, suffix: string): {
  draft: AcceptanceArticle;
  due: AcceptanceArticle;
  future: AcceptanceArticle;
} {
  const base = {
    content: '<p>这是一条自动验收记录，验收完成后会被清理。</p>',
    summary: '自动验收记录',
    template: 'diary' as const,
    theme: '#c6a96b',
  };
  return {
    draft: {
      ...base,
      published_at: new Date(now.getTime() - 3_600_000).toISOString(),
      status: 'draft',
      title: '验收草稿：不可公开',
    },
    due: {
      ...base,
      published_at: new Date(now.getTime() - 3_600_000).toISOString(),
      slug: `acceptance-due-${suffix}`,
      status: 'scheduled',
      title: '验收到期排期：应自动公开',
    },
    future: {
      ...base,
      published_at: new Date(now.getTime() + 3_600_000).toISOString(),
      slug: `acceptance-future-${suffix}`,
      status: 'scheduled',
      title: '验收未来排期：不可提前公开',
    },
  };
}

class LiveDirectusClient {
  private token = '';

  constructor(
    private readonly baseUrl: string,
    private readonly email: string,
    private readonly password: string,
  ) {}

  async login(): Promise<void> {
    const response = await fetch(`${this.baseUrl}/auth/login`, {
      body: JSON.stringify({ email: this.email, password: this.password }),
      headers: { 'content-type': 'application/json' },
      method: 'POST',
    });
    if (!response.ok) throw new Error(`Live verification login failed (${response.status})`);
    const payload = (await response.json()) as { data?: { access_token?: string } };
    if (!payload.data?.access_token) throw new Error('Live verification received no access token');
    this.token = payload.data.access_token;
  }

  async request<T>(path: string, init?: RequestInit): Promise<T> {
    const response = await fetch(`${this.baseUrl}${path}`, {
      ...init,
      headers: {
        accept: 'application/json',
        authorization: `Bearer ${this.token}`,
        ...(init?.body ? { 'content-type': 'application/json' } : {}),
      },
    });
    if (!response.ok) throw new Error(`Live Directus request failed ${path} (${response.status})`);
    if (response.status === 204) return undefined as T;
    return (await response.json()) as T;
  }
}

async function anonymousArticleCount(baseUrl: string, slug: string): Promise<number> {
  const query = new URLSearchParams({ 'filter[slug][_eq]': slug, fields: 'id', limit: '1' });
  const response = await fetch(`${baseUrl}/items/articles?${query}`, {
    headers: { accept: 'application/json' },
  });
  if (!response.ok) throw new Error(`Anonymous article probe failed (${response.status})`);
  const payload = (await response.json()) as { data?: unknown[] };
  return payload.data?.length ?? 0;
}

function requireEnvironment(environment: NodeJS.ProcessEnv, name: string): string {
  const value = environment[name];
  if (!value) throw new Error(`${name} is required`);
  return value.replace(/\/+$/, '');
}

export async function verifyLive(environment = process.env): Promise<Record<string, unknown>> {
  const directusUrl = requireEnvironment(environment, 'DIRECTUS_URL');
  const frontendUrl = requireEnvironment(environment, 'FRONTEND_URL');
  const email = requireEnvironment(environment, 'DIRECTUS_ADMIN_EMAIL');
  const password = requireEnvironment(environment, 'DIRECTUS_ADMIN_PASSWORD');
  const previewSecret = requireEnvironment(environment, 'PREVIEW_SECRET');
  const client = new LiveDirectusClient(directusUrl, email, password);
  await client.login();

  const health = await client.request<{ status: string }>('/server/health');
  if (!['ok', 'warn'].includes(health.status)) throw new Error(`Directus health is ${health.status}`);

  const fixtures = buildAcceptanceFixtures(new Date(), String(Date.now()));
  const createdIds: Array<number | string> = [];
  try {
    for (const fixture of [fixtures.draft, fixtures.future, fixtures.due]) {
      const payload = await client.request<{ data: { id: number | string; slug: string } }>('/items/articles', {
        body: JSON.stringify(fixture),
        method: 'POST',
      });
      createdIds.push(payload.data.id);
      if (fixture === fixtures.draft) fixture.slug = payload.data.slug;
    }
    if (!fixtures.draft.slug || !/^post-[a-f0-9]{10}$/.test(fixtures.draft.slug)) {
      throw new Error('Blank article slug was not generated by the Directus hook');
    }

    const [
      draftCount,
      futureCount,
      dueCount,
      draftPage,
      futurePage,
      duePage,
      formalPage,
      wrongPreview,
      correctPreview,
    ] =
      await Promise.all([
        anonymousArticleCount(directusUrl, fixtures.draft.slug),
        anonymousArticleCount(directusUrl, fixtures.future.slug),
        anonymousArticleCount(directusUrl, fixtures.due.slug),
        fetch(`${frontendUrl}/posts/${fixtures.draft.slug}`),
        fetch(`${frontendUrl}/posts/${fixtures.future.slug}`),
        fetch(`${frontendUrl}/posts/${fixtures.due.slug}`),
        fetch(`${frontendUrl}/posts/startup-vs-speculation`),
        fetch(`${frontendUrl}/preview/posts/${fixtures.draft.slug}?secret=invalid-secret`),
        fetch(
          `${frontendUrl}/preview/posts/${fixtures.draft.slug}?secret=${encodeURIComponent(previewSecret)}`,
        ),
      ]);

    const expected = {
      draftApiCount: 0,
      draftPageStatus: 404,
      dueApiCount: 1,
      duePageStatus: 200,
      formalPageStatus: 200,
      futureApiCount: 0,
      futurePageStatus: 404,
      previewPageStatus: 200,
      wrongPreviewStatus: 404,
    };
    const actual = {
      draftApiCount: draftCount,
      draftPageStatus: draftPage.status,
      dueApiCount: dueCount,
      duePageStatus: duePage.status,
      formalPageStatus: formalPage.status,
      futureApiCount: futureCount,
      futurePageStatus: futurePage.status,
      previewPageStatus: correctPreview.status,
      wrongPreviewStatus: wrongPreview.status,
    };
    if (JSON.stringify(actual) !== JSON.stringify(expected)) {
      throw new Error(`Live publication gate mismatch: ${JSON.stringify(actual)}`);
    }
    const cacheControl = correctPreview.headers.get('cache-control') ?? '';
    const robots = correctPreview.headers.get('x-robots-tag') ?? '';
    if (!cacheControl.includes('no-store') || !robots.includes('noindex')) {
      throw new Error('Preview response is missing private no-store/noindex headers');
    }
    return {
      ...actual,
      autoSlugGenerated: true,
      directusHealth: health.status,
      previewNoStore: true,
      previewNoIndex: true,
    };
  } finally {
    await Promise.allSettled(
      createdIds.map((id) => client.request(`/items/articles/${id}`, { method: 'DELETE' })),
    );
  }
}

async function main(): Promise<void> {
  process.stdout.write(`${JSON.stringify(await verifyLive())}\n`);
}

const entryPath = process.argv[1] ? pathToFileURL(process.argv[1]).href : '';
if (entryPath === import.meta.url) {
  main().catch((error: unknown) => {
    console.error(error instanceof Error ? error.message : 'Live verification failed');
    process.exitCode = 1;
  });
}
